services:
  - type: web
    name: ingredient-recipes-app
    env: python
    plan: free
    branch: main
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn wsgi:app"
    envVars:
      - fromGroup: ingredient-recipes-settings
      - key: DATABASE_URL
        fromDatabase:
          name: ingredient-recipes-db
          property: connectionString

envVarGroups:
  - name: ingredient-recipes-settings
    envVars:
      - key: ENV
        value: production
      - key: FLASK_APP
        value: wsgi.py
      - key: SECRET_KEY
        value: something-secret-and-random

databases:
  - name: ingredient-recipes-db
    plan: free
    databaseName: mydb
